# Generated by Django 2.1 on 2018-09-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
    ]
