# Generated by Django 2.1 on 2018-09-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
    ]
