# Generated by Django 2.1 on 2018-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180926_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='usuarios/', verbose_name='Logo'),
        ),
    ]
