# Generated by Django 2.1 on 2018-10-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181007_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nacimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='usuarios/', verbose_name='Imagem'),
        ),
    ]
