# Generated by Django 2.1 on 2018-10-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181008_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nacimento',
            field=models.DateField(blank=True, default='static/assets/img/avatar/default.jpg', verbose_name='Data de Nascimento'),
        ),
    ]
