# Generated by Django 2.1 on 2018-10-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181008_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='usuarios/', verbose_name='Imagem'),
        ),
    ]
