# Generated by Django 2.1 on 2018-10-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181008_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.CharField(blank=True, help_text='nome e sobrenome', max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, help_text='nome e sobrenome', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
