# Generated by Django 2.1 on 2018-09-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sus', models.CharField(max_length=20)),
                ('acompanhamento_com_especialista', models.BooleanField()),
                ('especialista', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(max_length=200)),
                ('idade_pai', models.IntegerField(default=0)),
                ('profissao_pai', models.CharField(max_length=200)),
                ('nome_mae', models.CharField(max_length=200)),
                ('idade_mae', models.IntegerField(default=0)),
                ('profissao_mae', models.CharField(max_length=200)),
                ('renda_familiar', models.FloatField(default=0)),
                ('bpc', models.BooleanField()),
                ('bolsa_familia', models.BooleanField()),
                ('aposentadoria', models.BooleanField()),
                ('benediciario', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=300)),
                ('numero_da_rua', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=200)),
                ('ponto_de_referencia', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('estuda_ensino_regular', models.BooleanField()),
                ('ano_estuda', models.CharField(max_length=50)),
                ('turma_estuda', models.CharField(max_length=50)),
                ('turno_estuda', models.CharField(max_length=50)),
                ('observacoes', models.CharField(max_length=50)),
                ('data_da_triagem', models.DateTimeField(verbose_name='Data da Triagem')),
                ('assinatura_proficinal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cid', models.CharField(max_length=20)),
                ('data_nacimento', models.DateTimeField(verbose_name='Data de Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('observacoes', models.CharField(max_length=300)),
                ('realizada', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Funcionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='triagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Usuario'),
        ),
    ]
