# Generated by Django 2.1.1 on 2018-09-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data da Aula')),
                ('conteudo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField()),
                ('abono', models.BooleanField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('turno', models.BooleanField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cid', models.CharField(max_length=20)),
                ('data_nacimento', models.DateTimeField(verbose_name='Data de Nascimento')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.Usuario'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.Turma'),
        ),
    ]
