# Generated by Django 2.1 on 2018-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0003_professorturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='dataFrequencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Frequencia'),
        ),
    ]
