# Generated by Django 2.1 on 2018-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0004_frequencia_datafrequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateField(verbose_name='Data da Aula'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='dataFrequencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Frequencia'),
        ),
    ]
