# Generated by Django 2.1 on 2018-10-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0005_auto_20181003_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='dataFrequencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Frequencia'),
        ),
    ]
