# Generated by Django 2.1 on 2018-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0008_auto_20181003_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.BooleanField(),
        ),
    ]
