# Generated by Django 2.1 on 2018-10-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0009_auto_20181003_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriagemPedagogica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('estuda', models.BooleanField()),
                ('anoEscolar', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('horarioApae', models.BooleanField()),
                ('alimentacao', models.TextField()),
                ('medicacao', models.TextField()),
                ('composicaoFamiliar', models.TextField()),
                ('controleUrinario', models.BooleanField()),
                ('controleEsfincter', models.BooleanField()),
                ('controleObservacao', models.TextField()),
                ('cuidador', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=50)),
                ('horarioDormir', models.FloatField()),
                ('horarioAcordar', models.FloatField()),
                ('dormeCom', models.CharField(max_length=50)),
                ('falaBem', models.BooleanField()),
                ('comunicacaoGestos', models.BooleanField()),
                ('gagueira', models.BooleanField()),
                ('enxergaBem', models.BooleanField()),
                ('destro', models.BooleanField()),
                ('fazBarulho', models.BooleanField()),
                ('anda', models.BooleanField()),
                ('seguraLapis', models.BooleanField()),
                ('sentaCorretamente', models.BooleanField()),
                ('caiMuito', models.BooleanField()),
                ('cansaFacil', models.BooleanField()),
                ('afetuodo', models.BooleanField()),
                ('medroso', models.BooleanField()),
                ('agressivo', models.BooleanField()),
                ('reageContrariado', models.BooleanField()),
                ('tique', models.BooleanField()),
                ('choraFacilidade', models.BooleanField()),
                ('sabeEspear', models.BooleanField()),
                ('obedeceOrdens', models.BooleanField()),
                ('fazAmizade', models.BooleanField()),
                ('isolase', models.BooleanField()),
                ('compartilha', models.BooleanField()),
                ('seRelaciona', models.BooleanField()),
                ('expressaPensanetos', models.BooleanField()),
                ('transmiteRecados', models.BooleanField()),
                ('descricaoUsuario', models.TextField()),
            ],
        ),
    ]
