# Generated by Django 2.1 on 2018-10-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0012_auto_20181004_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
    ]
