# Generated by Django 2.1 on 2018-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_triagem_qual'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/logo', verbose_name='Logo'),
        ),
    ]
