# Generated by Django 2.1 on 2018-09-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_triagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='acompanhamento_com_especialista',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], max_length=5),
        ),
    ]
