# Generated by Django 2.1 on 2018-09-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20180925_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.AlterField(
            model_name='triagem',
            name='assinatura_proficinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Funcionario'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Funcionario'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
