# Generated by Django 2.1 on 2018-09-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20180926_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='assinatura_proficinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Funcionario'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Funcionario'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
