# Generated by Django 2.1 on 2018-10-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20180926_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
