# Generated by Django 2.1 on 2018-10-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181005_1833'),
        ('social', '0010_auto_20181005_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data do término')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(default=0)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='visita',
            name='data_visita',
            field=models.DateTimeField(verbose_name='Data Visita'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lista',
            field=models.ManyToManyField(to='social.Lista'),
        ),
    ]
