# Generated by Django 2.1 on 2018-10-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20181005_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, verbose_name='Data do término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lista',
            field=models.ManyToManyField(blank=True, to='social.Lista'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lista',
            name='Usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='posicao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='acompanhamento_com_especialista',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='ano_estuda',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='aposentadoria',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='assinatura_proficinal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Funcionario'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='bairro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='benediciario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='bolsa_familia',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='bpc',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='cidade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='data_da_triagem',
            field=models.DateTimeField(blank=True, verbose_name='Data da Triagem'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='especialista',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='estuda_ensino_regular',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='idade_mae',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='idade_pai',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='numero_da_rua',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='observacoes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='ponto_de_referencia',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='profissao_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='profissao_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='qual',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='renda_familiar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='rua',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='sus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='turma_estuda',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='turno_estuda',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data_visita',
            field=models.DateTimeField(blank=True, verbose_name='Data Visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Funcionario'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='visita',
            name='realizada',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='visita',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
    ]
